{% set version = "0.4.0" %}

package:
  name: sccache
  version: {{ version }}

source:
  url: https://github.com/mozilla/sccache/archive/v{{ version }}.tar.gz
  sha256: 361d2e4150d5bf9a563face9113062335dab98f4c726ad58c4bc77252051e676

build:
  number: 0
  missing_dso_whitelist:   # [osx]
    - /usr/lib/libresolv.9.dylib  # [osx]

requirements:
  build:
    - rust
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
  host:
    - openssl

test:
  commands:
    - sccache --version
    - sccache --help

about:
  home: https://github.com/mozilla/sccache
  summary: sccache is ccache with cloud storage
  license: Apache-2.0
  license_file: LICENSE
  license_family: APACHE
  description: |
    Sccache is a ccache-like tool. It is used as a compiler wrapper and avoids
    compilation when possible, storing a cache in a remote storage using the
    Amazon Simple Cloud Storage Service (S3) API, the Google Cloud Storage (GCS) API,
    or Redis.
  doc_url: https://github.com/mozilla/sccache
  dev_url: https://github.com/mozilla/sccache

extra:
  recipe-maintainers:
    - luizirber
    - wolfv
    - jonashaag
